version: v1.0
name: Manual Release Pipeline with Dynamic Versioning

pipeline:
  jobs:
    - name: Tag and Release with Version from version.txt
      commands:
        - checkout
        - VERSION=$(cat version.txt)
        - echo "Version extracted: $VERSION"
        - git tag $VERSION
        - git push origin $VERSION